DATA_PATH = '../data/'
INTER_PATH = DATA_PATH + 'intermediate/'
KIPF_PATH = DATA_PATH + 'kipf-formated/'
POKEC_PATH = DATA_PATH + 'pokec/'
MOVIELK_PATH = DATA_PATH + 'ml-100k/'
MOVIELM_PATH = DATA_PATH + 'ml-25m/'
FAIRGNN_PATH = DATA_PATH + 'fairgnn-data/'
GEO_PATH = DATA_PATH + 'geo/'
DGL_PATH = DATA_PATH + 'dgl/'
MODELS_PATH = DATA_PATH + 'models/'
EMBEDDINGS_PATH = DATA_PATH + 'embeds/'
PREDICTIONS_PATH = DATA_PATH + 'preds/'
RESULTS_PATH = DATA_PATH + 'results/'
PLOT_PATH = DATA_PATH + 'plots/'
SEED = 47
PROJECT_NAME = 'gnn-fair-gcn'  # for wandb
GPU_USED = 'cpu'
CV_NUM = 10
